# Generated by Django 3.2.5 on 2021-11-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
