# Generated by Django 3.2.5 on 2021-12-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211107_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='note_feedback',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_feedbacks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
