# Generated by Django 3.2.5 on 2021-12-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211228_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_number_of_afs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
