# Generated by Django 3.2.5 on 2021-12-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_total_number_of_afs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='total_number_of_afs',
            new_name='total_number_of_ads',
        ),
    ]
