# Generated by Django 3.2.5 on 2022-01-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_total_number_of_afs_customuser_total_number_of_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='intro',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', max_length=21),
        ),
    ]
