# Generated by Django 3.2.5 on 2021-10-23 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211015_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
