# Generated by Django 3.2.5 on 2022-01-03 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatroom_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='created_room_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_updated_room_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
