# Generated by Django 3.2.5 on 2021-08-29 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import records.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_state', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('date_of_meeting', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('meeting_code', models.CharField(max_length=25)),
                ('delivery_code', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PropositionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('state', models.BooleanField()),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_items', to='records.proposition')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moyen_de_transport', models.CharField(max_length=50)),
                ('city_destination', models.CharField(max_length=50)),
                ('city_arrival', models.CharField(max_length=50)),
                ('min_price', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('max_volume', records.utils.IntegerRangeField()),
                ('description', models.CharField(max_length=250)),
                ('categories', models.JSONField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('accepted', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_records', to='records.record')),
            ],
        ),
        migrations.CreateModel(
            name='PropositionItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='records.propositionitem')),
            ],
        ),
        migrations.AddField(
            model_name='proposition',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='records.record'),
        ),
    ]
