# Generated by Django 3.2.5 on 2021-08-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_propositionitemimage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionitem',
            name='proposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposition_items', to='records.proposition'),
        ),
    ]
