# Generated by Django 3.2.5 on 2021-08-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_propositionitem_proposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propositionitem',
            name='unit',
        ),
        migrations.AlterField(
            model_name='proposition',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='address_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='date_of_meeting',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='meeting_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propositionitem',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
