# Generated by Django 3.2.5 on 2021-08-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20210830_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
