# Generated by Django 3.2.5 on 2021-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_propositionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionitem',
            name='state',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Undefined', max_length=255),
        ),
    ]
