# Generated by Django 3.2.5 on 2021-09-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_propositionitem_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='address_state',
            field=models.CharField(choices=[('Undefined', 'Undefined'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Undefined', max_length=255),
        ),
    ]
