# Generated by Django 3.2.5 on 2021-09-07 23:04

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_proposition_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='meeting_code',
            field=models.CharField(default=records.models.random_number, max_length=4),
        ),
    ]
