# Generated by Django 3.2.5 on 2021-09-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_proposition_meeting_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='delivery_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposition',
            name='meeting_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
