# Generated by Django 3.2.5 on 2021-09-07 23:29

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20210907_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='delivery_code',
            field=models.CharField(default=records.models.random_number, max_length=25),
        ),
    ]
