# Generated by Django 3.2.5 on 2021-09-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_proposition_delivery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='moyen_de_transport',
            field=models.CharField(choices=[('Car', 'Car'), ('Avion', 'Avion'), ('Bateau', 'Bateau')], max_length=50),
        ),
    ]
