# Generated by Django 3.2.5 on 2021-09-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import records.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0015_askrecord_askrecorditem_askrecorditemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askrecord',
            name='city_arrival',
        ),
        migrations.RemoveField(
            model_name='askrecord',
            name='city_destination',
        ),
        migrations.RemoveField(
            model_name='askrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='askrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='askrecord',
            name='description',
        ),
        migrations.RemoveField(
            model_name='askrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='record',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='record',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='record',
            name='max_volume',
        ),
        migrations.RemoveField(
            model_name='record',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='record',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='record',
            name='moyen_de_transport',
        ),
        migrations.AddField(
            model_name='askrecord',
            name='record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ask_record', to='records.record'),
        ),
        migrations.AddField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProposeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen_de_transport', models.CharField(choices=[('Car', 'Car'), ('Avion', 'Avion'), ('Bateau', 'Bateau')], max_length=50)),
                ('min_price', models.PositiveIntegerField()),
                ('max_weight', models.PositiveIntegerField()),
                ('max_volume', records.utils.IntegerRangeField()),
                ('categories', models.JSONField()),
                ('record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propose_record', to='records.record')),
            ],
        ),
        migrations.AlterField(
            model_name='subrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_records', to='records.proposerecord'),
        ),
    ]
