# Generated by Django 3.2.5 on 2021-09-19 15:59

from django.db import migrations, models
import django.db.models.deletion
import records.utils


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20210918_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposerecord',
            name='record',
        ),
        migrations.AddField(
            model_name='record',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='max_volume',
            field=records.utils.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='max_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='moyen_de_transport',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Avion', 'Avion'), ('Bateau', 'Bateau')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('Propose', 'Propose'), ('Ask', 'Ask')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='askrecorditem',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ask_items', to='records.record'),
        ),
        migrations.AlterField(
            model_name='subrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_records', to='records.record'),
        ),
        migrations.DeleteModel(
            name='AskRecord',
        ),
        migrations.DeleteModel(
            name='ProposeRecord',
        ),
    ]
