# Generated by Django 3.2.5 on 2021-09-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_auto_20210919_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
