# Generated by Django 3.2.5 on 2021-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_proposition_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='proposition_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=255, null=True),
        ),
    ]
