# Generated by Django 3.2.5 on 2021-09-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_askrecorditem_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='proposition_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
