# Generated by Django 3.2.5 on 2021-09-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_alter_proposition_proposition_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='propositionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
