# Generated by Django 3.2.5 on 2021-09-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_auto_20210921_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propositionitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='propositionitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='proposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
