# Generated by Django 3.2.5 on 2021-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_auto_20210922_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
