# Generated by Django 3.2.5 on 2021-10-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_auto_20211019_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='proposition',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='feedback_left',
        ),
    ]
