# Generated by Django 3.2.5 on 2021-10-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_alter_record_moyen_de_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
