# Generated by Django 3.2.5 on 2021-11-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0031_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
