# Generated by Django 3.2.5 on 2021-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0032_record_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
