# Generated by Django 3.2.5 on 2021-12-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0033_record_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_form', models.BooleanField(default=False)),
                ('reg_form', models.BooleanField(default=False)),
                ('login_form', models.BooleanField(default=False)),
                ('annonce_form', models.BooleanField(default=False)),
                ('demande_form', models.BooleanField(default=False)),
                ('search_form', models.BooleanField(default=False)),
            ],
        ),
    ]
