# Generated by Django 3.2.5 on 2021-12-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0034_captcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrecord',
            name='max_weight',
            field=models.FloatField(),
        ),
    ]
