# Generated by Django 3.2.5 on 2022-01-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0035_alter_subrecord_max_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='Proposed_city_arrival',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='Proposed_city_destination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='Proposed_home_delivery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='Proposed_moyen_de_transport',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Avion', 'Avion')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='generated_image_ask',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='record',
            name='generated_image_propose',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
