# Generated by Django 3.2.5 on 2022-01-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0036_auto_20220120_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='Proposed_city_arrival',
            new_name='Proposed_city_arrivalp',
        ),
    ]
