# Generated by Django 3.2.5 on 2022-01-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0037_rename_proposed_city_arrival_proposition_proposed_city_arrivalp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='Proposed_city_arrivalp',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='Proposed_city_destination',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='Proposed_home_delivery',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='Proposed_moyen_de_transport',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='date',
        ),
    ]
