# Generated by Django 3.2.5 on 2022-01-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0040_auto_20220120_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='generated_imagefor_ask',
        ),
        migrations.RemoveField(
            model_name='record',
            name='generated_imagefor_propose',
        ),
    ]
