# Generated by Django 3.2.5 on 2022-01-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0041_auto_20220120_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image_ask',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='record',
            name='image_propose',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
