# Generated by Django 3.2.5 on 2022-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0044_auto_20220120_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
