# Generated by Django 3.2.5 on 2022-01-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0046_auto_20220121_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
