# Generated by Django 3.2.5 on 2022-01-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0047_alter_record_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='min_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
