# Generated by Django 3.2.5 on 2022-01-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0050_auto_20220122_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='rje_image_ask',
        ),
        migrations.RemoveField(
            model_name='record',
            name='rje_image_propose',
        ),
    ]
