# Generated by Django 3.2.5 on 2022-01-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0052_remove_record_ask_item_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='categories',
            field=models.JSONField(blank=True, default=['Food'], null=True),
        ),
    ]
