# Generated by Django 3.2.5 on 2022-02-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0053_alter_record_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
