# Generated by Django 3.2.5 on 2022-02-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0054_auto_20220209_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
