# Generated by Django 3.2.5 on 2022-02-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0055_alter_record_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ask_total_price',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ask_total_weight',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='max_weight',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='min_price',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
