# Generated by Django 3.2.5 on 2022-02-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0056_auto_20220212_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=23)),
                ('objet', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
