# Generated by Django 3.2.5 on 2022-02-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0057_contactnous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnous',
            name='email',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactnous',
            name='message',
            field=models.CharField(blank=True, default='null', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactnous',
            name='name',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactnous',
            name='objet',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactnous',
            name='phone_number',
            field=models.CharField(blank=True, default='null', max_length=23, null=True),
        ),
    ]
