# Generated by Django 3.2.5 on 2022-03-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0058_auto_20220219_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ask_total_price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ask_total_weight',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
