# Generated by Django 3.2.5 on 2022-03-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0059_auto_20220315_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrecord',
            name='price',
            field=models.FloatField(),
        ),
    ]
