# Generated by Django 3.2.5 on 2022-03-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0060_alter_subrecord_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askrecorditem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='askrecorditem',
            name='weight',
            field=models.FloatField(),
        ),
    ]
