# Generated by Django 3.2.5 on 2022-04-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0062_auto_20220401_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
