# Generated by Django 3.2.5 on 2022-04-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0063_alter_record_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
    ]
