# Generated by Django 3.2.5 on 2022-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0067_record_cost_by_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='cost_by_kg',
            field=models.DecimalField(blank=True, decimal_places=1, default=4, max_digits=5, null=True),
        ),
    ]
