# Generated by Django 3.2.5 on 2022-04-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0068_alter_record_cost_by_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='price_proposed',
            field=models.DecimalField(blank=True, decimal_places=1, default=10, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='weight_items',
            field=models.DecimalField(blank=True, decimal_places=1, default=3, max_digits=5, null=True),
        ),
    ]
