# Generated by Django 3.2.5 on 2022-04-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0069_auto_20220405_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='MultiDepart',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
