# Generated by Django 3.2.5 on 2022-04-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0070_record_multidepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='MultiDest',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
