const cities = [
  {
    label: "None",
    value: "",
  },
  {

    label: "France",
    options: [
      { value: "Paris, France", label: "Paris" },
      { value: "Marseille, France", label: "Marseille" },
      { value: "Lyon, France", label: "Lyon" },
      { value: "Toulouse, France", label: "Toulouse" },
      { value: "Nice, France", label: "Nice" },
      { value: "Nantes, France", label: "Nantes" },
      { value: "Montpellier, France", label: "Montpellier" },
      { value: "Strasbourg, France", label: "Strasbourg" },
      { value: "Bordeaux, France", label: "Bordeaux" },
      { value: "Lille, France", label: "Lille" },
      { value: "Alsace, France", label: "Alsace" },
      { value: "Aquitaine, France", label: "Aquitaine" },
      { value: "Auvergne, France", label: "Auvergne" },
      { value: "Basse-Normandie, France", label: "Basse-Normandie" },
      { value: "Bourgogne, France", label: "Bourgogne" },
      { value: "Bretagne, France", label: "Bretagne" },
      { value: "Centre, France", label: "Centre" },
      { value: "Champagne-Ardenne, France", label: "Champagne-Ardenne" },
      { value: "Corse, France", label: "Corse" },
      { value: "Franche-Comté, France", label: "Franche-Comté" },
      { value: "Haute-Normandie, France", label: "Haute-Normandie" },
      { value: "Ile-de-France, France", label: "Ile-de-France" },
      { value: "Languedoc-Roussillon, France", label: "Languedoc-Roussillon" },
      { value: "Limousin, France", label: "Limousin" },
      { value: "Lorraine, France", label: "Lorraine" },
      { value: "Midi-Pyrénées, France", label: "Midi-Pyrénées" },
      { value: "Nord-Pas-de-Calais, France", label: "Nord-Pas-de-Calais" },
      { value: "Pays de la Loire, France", label: "Pays de la Loire" },
      { value: "Picardie, France", label: "Picardie" },
      { value: "Poitou-Charentes, France", label: "Poitou-Charentes" },
      {
        value: "Provence-Alpes-Côte d'Azur, France",
        label: "Provence-Alpes-Côte d'Azur",
      },
      { value: "Rhône-Alpes, France", label: "Rhône-Alpes" },
      { value: "Guadeloupe, France", label: "Guadeloupe" },
      { value: "Martinique, France", label: "Martinique" },
      { value: "Guyane, France", label: "Guyane" },
      { value: "Réunion, France", label: "Réunion" },
    ],
  },
  {
    label: "Italy",
    options: [
      { value: "Rome, Italy", label: "Rome" },
      { value: "Milan, Italy", label: "Milan" },
      { value: "Naples, Italy", label: "Naples" },
      { value: "Turin, Italy", label: "Turin" },
      { value: "Palermo, Italy", label: "Palermo" },
      { value: "Genoa, Italy", label: "Genoa" },
      { value: "Bologna, Italy", label: "Bologna" },
      { value: "Florence, Italy", label: "Florence" },
      { value: "Catania, Italy", label: "Catania" },
      { value: "Bari, Italy", label: "Bari" },
      { value: "Messina, Italy", label: "Messina" },
      { value: "Verona, Italy", label: "Verona" },
      { value: "Abruzzo, Italy", label: "Abruzzo" },
      { value: "Basilicata, Italy", label: "Basilicata" },
      { value: "Calabria, Italy", label: "Calabria" },
      { value: "Campania, Italy", label: "Campania" },
      { value: "Emilia-Romagna, Italy", label: "Emilia-Romagna" },
      { value: "Friuli-Venezia Giulia, Italy", label: "Friuli-Venezia" },
      { value: "Lazio, Italy", label: "Lazio" },
      { value: "Liguria, Italy", label: "Liguria" },
      { value: "Lombardia, Italy", label: "Lombardia" },
      { value: "Marche, Italy", label: "Marche" },
      { value: "Molise, Italy", label: "Molise" },
      { value: "Piemonte, Italy", label: "Piemonte" },
      { value: "Puglia, Italy", label: "Puglia" },
      { value: "Sardegna, Italy", label: "Sardegna" },
      { value: "Sicialia, Italy", label: "Sicialia" },
      { value: "Toscana , Italy", label: "Toscana" },
      { value: "Trentino-Alto Adige, Italy", label: "Trentino-Alto Adige" },
      { value: "Umbria, Italy", label: "Umbria" },
      { value: "Valle d'Aosta, Italy", label: "Valle d'Aosta" },
      { value: "Veneto, Italy", label: "Veneto" },
    ],
  },
  {
    label: "Allemagne",
    options: [
      { value: "Berlin, Allemagne", label: "Berlin" },
      { value: "Hambourg, Allemagne", label: "Hambourg" },
      { value: "Munich, Allemagne", label: "Munich" },
      { value: "Cologne, Allemagne", label: "Cologne" },
      { value: "Francfort-sur-le-Main, Allemagne", label: "Francfort-sur-le-Main" },
      { value: "Stuttgart, Allemagne", label: "Stuttgart" },
      { value: "Düsseldorf, Allemagne", label: "Düsseldorf" },
      { value: "Dortmund, Allemagne", label: "Dortmund" },
      { value: "Essen, Allemagne", label: "Essen" },
      { value: "Leipzig, Allemagne", label: "Leipzig" },
      { value: "Brême, Allemagne", label: "Brême" },
      { value: "Dresde, Allemagne", label: "Dresde" },
      { value: "Hanovre, Allemagne", label: "Hanovre" },

      { value: "Baden-Württemberg, Allemagne", label: "Baden-Württemberg" },
      { value: "Bayern, Allemagne", label: "Bayern" },
      
      { value: "Brandenburg, Allemagne", label: "Brandenburg" },
      { value: "Bremen, Allemagne", label: "Bremen" },
      { value: "Hamburg, Allemagne", label: "Hamburg" },
      { value: "Hessen, Allemagne", label: "Hessen" },
      {
        value: "Mecklenburg-Vorpommern, Allemagne",
        label: "Mecklenburg-Vorpommern",
      },
      { value: "Niedersachsen, Allemagne", label: "Niedersachsen" },
      { value: "Nordrhein-Westfalen, Allemagne", label: "Nordrhein-Westfalen" },
      { value: "Rheinland-Pfalz, Allemagne", label: "Rheinland-Pfalz" },
      { value: "Saarland, Allemagne", label: "Saarland" },
      { value: "Sachsen, Allemagne", label: "Sachsen" },
      { value: "Sachsen-Anhalt, Allemagne", label: "Sachsen-Anhalt" },
      { value: "Schleswig-Holstein, Allemagne", label: "Schleswig-Holstein" },
      { value: "Thüringen, Allemagne", label: "Thüringen" },
    ],
  },
  {
    label: "Espagne",
    options: [
      { value: "Andalusia, Espagne", label: "Andalusia" },
      { value: "Valencia, Espagne", label: "Valencia" },
      { value: "Catalonia, Espagne", label: "Catalonia" },
      { value: "Balearic Island, Espagne", label: "Balearic Island" },
      { value: "Canary Islands, Espagne", label: "Canary Islands" },
      { value: "Galicia, Espagne", label: "Galicia" },
      { value: "Basque, Espagne", label: "Basque" },
      { value: "Madrid, Espagne", label: "Madrid" },
      { value: "Asturia, Espagne", label: "Asturia" },
      { value: "Cantabri, Espagne", label: "Cantabri" },
      { value: "Murci, Espagne", label: "Murci" },
      { value: "Navarr, Espagne", label: "Navarr" },
      { value: "La Rioj, Espagne", label: "La Rioj" },
      { value: "Landlocked Arago, Espagne", label: "Landlocked" },
      { value: "Castil, Espagne", label: "Castil" },
      { value: "Castilla La Manch, Espagne", label: "Castilla La Manch" },
      { value: "Extremadur, Espagne", label: "Extremadur" },
    ],
  },
  {
    label: "Other Europe Countries",
    options: [
      {
        label: "Angleterre",
        value: "Angleterre",
      },
      {
        label: "Belgique",
        value: "Belgique",
      },
      {
        label: "Suisse",
        value: "Suisse",
      },
      {
        label: "Pays Bas",
        value: "Pays Bas",
      },
      {
        label: "Autriche",
        value: "Autriche",
      },
      {
        label: "Grece",
        value: "Grece",
      },
      {
        label: "Turquie",
        value: "Turquie",
      },
      {
        label: "Bulgarie",
        value: "Bulgarie",
      },
      {
        label: "Serbie",
        value: "Serbie",
      },
      {
        label: "Luxembourg",
        value: "Luxembourg",
      },
      {
        label: "Sweden",
        value: "Sweden",
      },
      {
        label: "Norway",
        value: "Norway",
      },
      {
        label: "Poland",
        value: "Poland",
      },
      {
        label: "Iceland",
        value: "Iceland",
      },
      {
        label: "Romania",
        value: "Romania",
      },
      {
        label: "Republique tcheque",
        value: "Republique tcheque",
      },
      {
        label: "Hollanda",
        value: "Hollanda",
      },
    ],
  },

  {
    label: "Tunisie",
    options: [
      { value: "Tunis, Tunisie", label: "Tunis" },
      { value: "Sfax, Tunisie", label: "Sfax" },
      { value: "Nabeul, Tunisie", label: "Nabeul" },
      { value: "Sousse, Tunisie", label: "Sousse" },
      { value: "Ben Arous, Tunisie", label: "Ben Arous" },
      { value: "Ariana, Tunisi", label: "Ariana" },
      { value: "Kairouan, Tunisie", label: "Kairouan" },
      { value: "Bizerte, Tunisie", label: "Bizerte" },
      { value: "Monastir, Tunisie", label: "Monastir" },
      { value: "Medenine, Tunisie", label: "Medenine" },
      { value: "Kasserine, Tunisie", label: "Kasserine" },
      { value: "Sidi Bouzid, Tunisie", label: "Sidi Bouzid" },
      { value: "Mahdia, Tunisie", label: "Mahdia" },
      { value: "Jendouba, Tunisie", label: "Jendouba" },
      { value: "Manouba, Tunisie", label: "Manouba" },
      { value: "Gabès, Tunisie", label: "Gabès" },
      { value: "Gafsa, Tunisie", label: "Gafsa" },
      { value: "Béja, Tunisie", label: "Béja" },
      { value: "Kef, Tunisie", label: "Kef" },
      { value: "Siliana, Tunisie", label: "Siliana" },
      { value: "Zaghouan, Tunisie", label: "Zaghouan" },
      { value: "Kebili, Tunisi", label: "Kebili" },
      { value: "Tataouine, Tunisie", label: "Tataouine" },
      { value: "Tozeur, Tunisie", label: "Tozeur" },
    ],
  },
  {
    label: "Algérie",
    options: [
      { value: "Alger, Algérie", label: "Alger" },
      { value: "Sétif, Algérie", label: "Sétif" },
      { value: "Oran, Algérie", label: "Oran" },
      { value: "Tizi Ouzou, Algérie", label: "Tizi Ouzou" },
      { value: "Batna, Algérie", label: "Batna" },
      { value: "Djelfa, Algérie", label: "Djelfa" },
      { value: "Blid, Algérie", label: "Blid" },
      { value: "Chlef, Algérie", label: "Chlef" },
      { value: "M'Sila, Algérie", label: "M" },
      { value: "Tlemcen, Algérie", label: "Tlemcen" },
      { value: "Constantine, Algérie", label: "Constantine" },
      { value: "Béjaïa, Algérie", label: "Béjaïa" },
      { value: "Skikda, Algérie", label: "Skikda" },
      { value: "Tiaret, Algérie", label: "Tiaret" },
      { value: "Médéa, Algérie", label: "Médéa" },
      { value: "Boumerdès, Algérie", label: "Boumerdès" },
      { value: "Mascara, Algérie", label: "Mascara" },
      { value: "Mila, Algérie", label: "Mila" },
      { value: "Aïn Defla, Algérie", label: "Aïn Defla" },
      { value: "Mostaganem, Algérie", label: "Mostaganem" },
      { value: "Relizane, Algérie", label: "Relizane" },
      { value: "Biskra, Algérie", label: "Biskra" },
      { value: "Bouira, Algérie", label: "Bouira" },
      { value: "Tébessa, Algérie", label: "Tébessa" },
      { value: "El Oued, Algérie", label: "El Oued" },
      { value: "Jijel, Algérie", label: "Jijel" },
      { value: "Bordj Bou Arreridj, Algérie", label: "Bordj Bou Arreridj" },
      { value: "Oum El Bouaghi, Algérie", label: "Oum El Bouaghi" },
      { value: "Annaba, Algérie", label: "Annaba" },
      { value: "Sidi Bel Abbès, Algérie", label: "Sidi Bel Abbès" },
      { value: "Tipaza, Algérie", label: "Tipaza" },
      { value: "Ouargla, Algérie", label: "Ouargla" },
      { value: "Guelma, Algérie", label: "Guelma" },
      { value: "Laghouat, Algérie", label: "Laghouat" },
      { value: "Souk Ahras, Algérie", label: "Souk" },
      { value: "El Tarf, Algérie", label: "El Tarf" },
      { value: "Adrar, Algérie", label: "Adrar" },
      { value: "Khenchela, Algérie", label: "Khenchela" },
      { value: "Aïn Témouchent, Algérie", label: "Aïn Témouchent" },
      { value: "Ghardaïa, Algérie", label: "Ghardaïa" },
      { value: "Saïda, Algérie", label: "Saïda" },
      { value: "Tissemsilt, Algérie", label: "Tissemsilt" },
      { value: "Béchar, Algérie", label: "Béchar" },
      { value: "El Bayadh, Algérie", label: "El Bayadh" },
      { value: "Naâma, Algérie", label: "Naâma" },
      { value: "Tamanrasset, Algérie", label: "Tamanrasset" },
      { value: "Illizi, Algérie", label: "Illizi" },
      { value: "Tindouf, Algérie", label: "Tindouf" },
    ],
  },
  {
    label: "Maroc",
    options: [
      { value: "Tanger, Maroc", label: "Tanger" },
      { value: "L'Oriental, Maroc", label: "L'Oriental" },
      { value: "Fès, Maroc", label: "Fès" },
      { value: "Rabat, Maroc", label: "Rabat" },
      { value: "Beni Mellal, Maroc", label: "Beni" },
      { value: "Casablanca, Maroc", label: "Casablanca" },
      { value: "Marrakech, Maroc", label: "Marrakech" },
      { value: "Drâa, Maroc", label: "Drâa" },
      { value: "Souss, Maroc", label: "Souss" },
      { value: "Guelmim, Maroc", label: "Guelmim" },
      { value: "Laâyoune, Maroc", label: "Laâyoune" },
      { value: "Dakhla, Maroc", label: "Dakhla" },
    ],
  },
  {
    label: "Libia",
    options: [
      { value: "Benghazi, Libia", label: "Benghazi" },
      { value: "Kufrah, Libia", label: "Kufrah" },
      { value: "Misurata, Libia", label: "Misurata" },
      { value: "Sabha, Libia", label: "Sabha" },
      { value: "Tripoli, Libia", label: "Tripoli" },
      { value: "Zintan, Libia", label: "Zintan" },
    ],
  },
  {
    label: "Egypt",
    options: [
      { value: "Cairo, Egypt", label: "Cairo" },
      { value: "Giza, Egypt", label: "Giza" },
      { value: "Qalyubia, Egypt", label: "Qalyubia" },
      { value: "Alexandria, Egypt", label: "Alexandria" },
      { value: "Beheira, Egypt", label: "Beheira" },
      { value: "Matruh, Egypt", label: "Matruh" },
      { value: "Damietta, Egypt", label: "Damietta" },
      { value: "Monufia, Egypt", label: "Monufia" },
      { value: "Gharbia, Egypt", label: "Gharbia" },
      { value: "Kafr El Sheikh, Egypt", label: "Kafr El Sheikh" },
      { value: "Dakahlia, Egypt", label: "Dakahlia" },
      { value: "Sharqia, Egypt", label: "Sharqia" },
      { value: "Port Said, Egypt", label: "Port Said" },
      { value: "Ismailia, Egypt", label: "Ismailia" },
      { value: "Suez, Egypt", label: "Suez" },
      { value: "North Sinai, Egypt", label: "North Sinai" },
      { value: "South Sinai, Egypt", label: "South Sinai" },
      { value: "Minya, Egypt", label: "Minya" },
      { value: "Beni Suef, Egypt", label: "Beni Suef" },
      { value: "Faiyum, Egypt", label: "Faiyum" },
      { value: "Asyut, Egypt", label: "Asyut" },
      { value: "New Valley, Egypt", label: "New Valley" },
      { value: "Sohag, Egypt", label: "Sohag" },
      { value: "Qena, Egypt", label: "Qena" },
      { value: "Luxor, Egypt", label: "Luxor" },
      { value: "Aswan, Egypt", label: "Aswan" },
      { value: "Red Sea, Egypt", label: "Red Sea" },
    ],
  },
];

export default cities;
