# Generated by Django 3.2.5 on 2021-10-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_auto_20210922_1856'),
        ('notifications', '0002_auto_20211012_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Proposition', 'Proposition')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PropositionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_notifications', to='notifications.notification')),
                ('proposition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propositin_notifications', to='records.proposition')),
            ],
        ),
    ]
