# Generated by Django 3.2.5 on 2021-10-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_auto_20210922_1856'),
        ('notifications', '0003_auto_20211013_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionnotification',
            name='notification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_notification', to='notifications.notification'),
        ),
        migrations.AlterField(
            model_name='propositionnotification',
            name='proposition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_notifications', to='records.proposition'),
        ),
    ]
