# Generated by Django 3.2.5 on 2021-10-23 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211015_1739'),
        ('notifications', '0005_alter_propositionnotification_proposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Proposition', 'Proposition'), ('Message', 'Message')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='chat.message')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_notification', to='notifications.notification')),
            ],
        ),
    ]
