# Generated by Django 3.2.5 on 2021-10-23 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211015_1739'),
        ('notifications', '0006_auto_20211022_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_notification', to='notifications.notification')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_notifications', to='chat.chatroom')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageNotification',
        ),
    ]
